require:
  - rubocop-rspec
  - ./spec/support/rubocop_patch

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_examples.rb'
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  IgnoredPatterns:
    - '\A\s*#'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_examples.rb'

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - 'as'

RSpec/ExampleLength:
  Max: 10

RSpec/ExampleWithoutDescription:
  EnforcedStyle: single_line_only

RSpec/ExampleWording:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - spec/integration/**/*

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  # Checks the style of children definitions at classes and modules.
  #
  # Our preferred style is compact-plus-one, which does not match any of the
  # existing styles, so we disable this cop.
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NestedParenthesizedCalls:
  Exclude:
    - 'spec/**/*_examples.rb'
    - 'spec/**/*_spec.rb'

Style/SingleLineBlockParams:
  # Prefer descriptive block param names.
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false
