require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - context
        - describe
        - wrap_context
      Skipped:
        - xcontext
        - xdescribe
        - xwrap_context
      Focused:
        - fcontext
        - fdescribe
        - fwrap_context
    Includes:
      Examples:
        - finclude_contract
        - finclude_examples
        - fwrap_examples
        - include_contract
        - include_examples
        - wrap_examples
        - xinclude_contract
        - xinclude_examples
        - xwrap_examples

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_examples.rb'
    - 'spec/**/*_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_examples.rb'

Naming/MethodParameterName:
  AllowedNames:
    - 'as'

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/BeNil:
  Enabled: false

RSpec/Eq:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/ExampleWithoutDescription:
  EnforcedStyle: single_line_only

RSpec/ExampleWording:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - spec/integration/**/*

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/LeadingSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/integration/**/*

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ClassAndModuleChildren:
  # Checks the style of children definitions at classes and modules.
  #
  # Our preferred style is compact-plus-one, which does not match any of the
  # existing styles, so we disable this cop.
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NestedParenthesizedCalls:
  Exclude:
    - 'spec/**/*_examples.rb'
    - 'spec/**/*_spec.rb'

Style/RedundantLineContinuation:
  # Broken for line continuation followed by start of do; end block.
  Enabled: false

Style/SingleLineBlockParams:
  # Prefer descriptive block param names.
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false
