plugins:
  - rubocop-rspec

inherit_gem:
  rspec-sleeping_king_studios: config/rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_examples.rb'
    - 'spec/**/*_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_examples.rb'

Naming/MethodParameterName:
  AllowedNames:
    - 'as'

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/BeNil:
  Enabled: false

RSpec/Eq:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/ExampleWithoutDescription:
  EnforcedStyle: single_line_only

RSpec/ExampleWording:
  Enabled: false

RSpec/ExpectInLet:
  # This is used extensively for generating expectations.
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/IncludeExamples:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/integration/**/*

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ClassAndModuleChildren:
  # Checks the style of children definitions at classes and modules.
  #
  # Our preferred style is compact-plus-one, which does not match any of the
  # existing styles, so we disable this cop.
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NestedParenthesizedCalls:
  Exclude:
    - 'spec/**/*_examples.rb'
    - 'spec/**/*_spec.rb'

Style/RedundantLineContinuation:
  # Broken for line continuation followed by start of do; end block.
  Enabled: false

Style/SingleLineBlockParams:
  # Prefer descriptive block param names.
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false
